version: "3"
services:
  postgres:
    image: "postgres:9.6.1"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "heuristica"
      POSTGRES_PASSWORD: "heuristica"
      POSTGRES_DB: "heuristica"