version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "universidade-das-heuristicas:backend"
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "universidade-das-heuristicas:frontend"
    ports:
      - "3000:3000"
    links:
      - "backend"